pipeline {
    agent any
    
    environment {
        PATH = "$HOME/.dotnet/tools:$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'cd API && dotnet build MyJourneyToWork.sln --configuration Release'
            }
        }
    }
}